# Create the channel pointing to Github path in the acm-demo-apps-channel namespace on 
# the ACM HUB. This YAML is not needed if the namespace and channel have already been created
# use 'oc get channel' or 'oc describe chennel *channel name*' to get details
 
apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  name: acm-demo-apps-channel
  namespace: acm-demo-apps-channel
spec:
  type: GitHub
  pathname: https://github.com/AdrianHammond/demo-apps.git