apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-helloworld-deployment
  labels:
    app: nodejs-helloworld
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs-helloworld
  template:
    metadata:
      labels:
        app: nodejs-helloworld
    spec:
      containers:
      - name: nodejs-helloworld
        image: quay.io/adrianhammond/nodejs-helloworld:v1.0
        ports:
        - containerPort: 8080
        env:
        - name: RELEASE
          value: "Stage Release v1.0.0"

---

apiVersion: v1
kind: Service
metadata:
  name: nodejs-helloworld-service
  namespace: nodejs-helloworld
spec:
  selector:
    app: nodejs-helloworld
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080

---

apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: nodejs-helloworld-route
  namespace: nodejs-helloworld
spec:
  path: /
  to:
    kind: Service
    name: nodejs-helloworld-service
  port:
    targetPort: 8080


