apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: nodejs-helloworld-clusters
  namespace: nodejs-helloworld
spec:
  clusterReplicas: 1
  clusterConditions:
    - type: ManagedClusterConditionAvailable
      status: "True"
  clusterSelector:
    matchLabels:
      env: demo