apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: nodejs-helloworld-application
  namespace: nodejs-helloworld
spec:
  componentKinds:
  - group: apps.open-cluster-management.io
    kind: Subscription
  descriptor: {}
  selector:
    matchLabels:
      app: nodejs-helloworld
      